// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: brokerproxy/v1/brokerproxy.proto

package brokerproxypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerProxy_Session_FullMethodName = "/brokerproxy.v1.BrokerProxy/Session"
)

// BrokerProxyClient is the client API for BrokerProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrokerProxy is the protocol between the always-on egress broker and the
// per-actor local proxy that is suspended and resumed with its actor. The
// stream dies on every actor suspend; the proxy redials on resume and resumes
// the event stream from its last acknowledged sequence number.
type BrokerProxyClient interface {
	// Session is one proxy connection. The first ProxyMsg MUST be an Announce;
	// the broker closes the stream otherwise. Identity of record is the
	// Announce, not the transport.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyMsg, BrokerMsg], error)
}

type brokerProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerProxyClient(cc grpc.ClientConnInterface) BrokerProxyClient {
	return &brokerProxyClient{cc}
}

func (c *brokerProxyClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyMsg, BrokerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrokerProxy_ServiceDesc.Streams[0], BrokerProxy_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyMsg, BrokerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerProxy_SessionClient = grpc.BidiStreamingClient[ProxyMsg, BrokerMsg]

// BrokerProxyServer is the server API for BrokerProxy service.
// All implementations must embed UnimplementedBrokerProxyServer
// for forward compatibility.
//
// BrokerProxy is the protocol between the always-on egress broker and the
// per-actor local proxy that is suspended and resumed with its actor. The
// stream dies on every actor suspend; the proxy redials on resume and resumes
// the event stream from its last acknowledged sequence number.
type BrokerProxyServer interface {
	// Session is one proxy connection. The first ProxyMsg MUST be an Announce;
	// the broker closes the stream otherwise. Identity of record is the
	// Announce, not the transport.
	Session(grpc.BidiStreamingServer[ProxyMsg, BrokerMsg]) error
	mustEmbedUnimplementedBrokerProxyServer()
}

// UnimplementedBrokerProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerProxyServer struct{}

func (UnimplementedBrokerProxyServer) Session(grpc.BidiStreamingServer[ProxyMsg, BrokerMsg]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedBrokerProxyServer) mustEmbedUnimplementedBrokerProxyServer() {}
func (UnimplementedBrokerProxyServer) testEmbeddedByValue()                     {}

// UnsafeBrokerProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerProxyServer will
// result in compilation errors.
type UnsafeBrokerProxyServer interface {
	mustEmbedUnimplementedBrokerProxyServer()
}

func RegisterBrokerProxyServer(s grpc.ServiceRegistrar, srv BrokerProxyServer) {
	// If the following call panics, it indicates UnimplementedBrokerProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerProxy_ServiceDesc, srv)
}

func _BrokerProxy_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrokerProxyServer).Session(&grpc.GenericServerStream[ProxyMsg, BrokerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerProxy_SessionServer = grpc.BidiStreamingServer[ProxyMsg, BrokerMsg]

// BrokerProxy_ServiceDesc is the grpc.ServiceDesc for BrokerProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brokerproxy.v1.BrokerProxy",
	HandlerType: (*BrokerProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _BrokerProxy_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "brokerproxy/v1/brokerproxy.proto",
}
