// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: brokerproxy/v1/brokerproxy.proto

package brokerproxypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ProxyMsg_Announce
	//	*ProxyMsg_Ack
	//	*ProxyMsg_Egress
	Msg           isProxyMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMsg) Reset() {
	*x = ProxyMsg{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMsg) ProtoMessage() {}

func (x *ProxyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMsg.ProtoReflect.Descriptor instead.
func (*ProxyMsg) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyMsg) GetMsg() isProxyMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ProxyMsg) GetAnnounce() *Announce {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMsg_Announce); ok {
			return x.Announce
		}
	}
	return nil
}

func (x *ProxyMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ProxyMsg) GetEgress() *Egress {
	if x != nil {
		if x, ok := x.Msg.(*ProxyMsg_Egress); ok {
			return x.Egress
		}
	}
	return nil
}

type isProxyMsg_Msg interface {
	isProxyMsg_Msg()
}

type ProxyMsg_Announce struct {
	Announce *Announce `protobuf:"bytes,1,opt,name=announce,proto3,oneof"`
}

type ProxyMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ProxyMsg_Egress struct {
	Egress *Egress `protobuf:"bytes,3,opt,name=egress,proto3,oneof"`
}

func (*ProxyMsg_Announce) isProxyMsg_Msg() {}

func (*ProxyMsg_Ack) isProxyMsg_Msg() {}

func (*ProxyMsg_Egress) isProxyMsg_Msg() {}

type BrokerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*BrokerMsg_Event
	//	*BrokerMsg_EgressResp
	Msg           isBrokerMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerMsg) Reset() {
	*x = BrokerMsg{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerMsg) ProtoMessage() {}

func (x *BrokerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerMsg.ProtoReflect.Descriptor instead.
func (*BrokerMsg) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{1}
}

func (x *BrokerMsg) GetMsg() isBrokerMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *BrokerMsg) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Msg.(*BrokerMsg_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *BrokerMsg) GetEgressResp() *EgressResp {
	if x != nil {
		if x, ok := x.Msg.(*BrokerMsg_EgressResp); ok {
			return x.EgressResp
		}
	}
	return nil
}

type isBrokerMsg_Msg interface {
	isBrokerMsg_Msg()
}

type BrokerMsg_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type BrokerMsg_EgressResp struct {
	EgressResp *EgressResp `protobuf:"bytes,2,opt,name=egress_resp,json=egressResp,proto3,oneof"`
}

func (*BrokerMsg_Event) isBrokerMsg_Msg() {}

func (*BrokerMsg_EgressResp) isBrokerMsg_Msg() {}

// Announce identifies the actor and resumes its event stream. Sent as the
// first frame on every (re)connect. The proxy reads atespace/name fresh from
// /run/ate at each connect: the identity mount is regenerated per resume and
// reads taken before a restore (e.g. in the golden-snapshot era) are stale.
type Announce struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Atespace string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// app_token lets the broker open (or keep) the real Slack Socket Mode
	// connection on the actor's behalf.
	AppToken string `protobuf:"bytes,3,opt,name=app_token,json=appToken,proto3" json:"app_token,omitempty"`
	// last_acked_seq resumes the stream: the broker drops buffered events with
	// seq <= last_acked_seq and re-sends the rest in order.
	LastAckedSeq  uint64 `protobuf:"varint,4,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announce) Reset() {
	*x = Announce{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announce) ProtoMessage() {}

func (x *Announce) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announce.ProtoReflect.Descriptor instead.
func (*Announce) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Announce) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *Announce) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Announce) GetAppToken() string {
	if x != nil {
		return x.AppToken
	}
	return ""
}

func (x *Announce) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

// Ack reports that the agent fully handled an event (acked it over the
// loopback Socket Mode connection). The broker drops the buffered event.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Event delivers one real Slack event. payload is the raw Socket Mode
// envelope JSON ({type, envelope_id, payload}) with its ORIGINAL envelope_id;
// delivery is at-least-once, so the agent de-duplicates by event timestamp.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{5}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Egress relays an agent's outbound Slack Web API call (chat.postMessage,
// auth.test, ...) for the broker to forward to real Slack.
type Egress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// corr_id correlates the EgressResp; unique per proxy connection.
	CorrId uint64 `protobuf:"varint,1,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// path is the URL path plus raw query, e.g. "/api/chat.postMessage".
	Path          string    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       []*Header `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte    `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Egress) Reset() {
	*x = Egress{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Egress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Egress) ProtoMessage() {}

func (x *Egress) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Egress.ProtoReflect.Descriptor instead.
func (*Egress) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{6}
}

func (x *Egress) GetCorrId() uint64 {
	if x != nil {
		return x.CorrId
	}
	return 0
}

func (x *Egress) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Egress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Egress) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Egress) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type EgressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrId        uint64                 `protobuf:"varint,1,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressResp) Reset() {
	*x = EgressResp{}
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressResp) ProtoMessage() {}

func (x *EgressResp) ProtoReflect() protoreflect.Message {
	mi := &file_brokerproxy_v1_brokerproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressResp.ProtoReflect.Descriptor instead.
func (*EgressResp) Descriptor() ([]byte, []int) {
	return file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP(), []int{7}
}

func (x *EgressResp) GetCorrId() uint64 {
	if x != nil {
		return x.CorrId
	}
	return 0
}

func (x *EgressResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EgressResp) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EgressResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_brokerproxy_v1_brokerproxy_proto protoreflect.FileDescriptor

const file_brokerproxy_v1_brokerproxy_proto_rawDesc = "" +
	"\n" +
	" brokerproxy/v1/brokerproxy.proto\x12\x0ebrokerproxy.v1\"\xa4\x01\n" +
	"\bProxyMsg\x126\n" +
	"\bannounce\x18\x01 \x01(\v2\x18.brokerproxy.v1.AnnounceH\x00R\bannounce\x12'\n" +
	"\x03ack\x18\x02 \x01(\v2\x13.brokerproxy.v1.AckH\x00R\x03ack\x120\n" +
	"\x06egress\x18\x03 \x01(\v2\x16.brokerproxy.v1.EgressH\x00R\x06egressB\x05\n" +
	"\x03msg\"\x80\x01\n" +
	"\tBrokerMsg\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x15.brokerproxy.v1.EventH\x00R\x05event\x12=\n" +
	"\vegress_resp\x18\x02 \x01(\v2\x1a.brokerproxy.v1.EgressRespH\x00R\n" +
	"egressRespB\x05\n" +
	"\x03msg\"}\n" +
	"\bAnnounce\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tapp_token\x18\x03 \x01(\tR\bappToken\x12$\n" +
	"\x0elast_acked_seq\x18\x04 \x01(\x04R\flastAckedSeq\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"3\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"4\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x93\x01\n" +
	"\x06Egress\x12\x17\n" +
	"\acorr_id\x18\x01 \x01(\x04R\x06corrId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x120\n" +
	"\aheaders\x18\x04 \x03(\v2\x16.brokerproxy.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"\x83\x01\n" +
	"\n" +
	"EgressResp\x12\x17\n" +
	"\acorr_id\x18\x01 \x01(\x04R\x06corrId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x120\n" +
	"\aheaders\x18\x03 \x03(\v2\x16.brokerproxy.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body2Q\n" +
	"\vBrokerProxy\x12B\n" +
	"\aSession\x12\x18.brokerproxy.v1.ProxyMsg\x1a\x19.brokerproxy.v1.BrokerMsg(\x010\x01BHZFgithub.com/ronlv10/substrate-ws-poc/proto/brokerproxy/v1;brokerproxypbb\x06proto3"

var (
	file_brokerproxy_v1_brokerproxy_proto_rawDescOnce sync.Once
	file_brokerproxy_v1_brokerproxy_proto_rawDescData []byte
)

func file_brokerproxy_v1_brokerproxy_proto_rawDescGZIP() []byte {
	file_brokerproxy_v1_brokerproxy_proto_rawDescOnce.Do(func() {
		file_brokerproxy_v1_brokerproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brokerproxy_v1_brokerproxy_proto_rawDesc), len(file_brokerproxy_v1_brokerproxy_proto_rawDesc)))
	})
	return file_brokerproxy_v1_brokerproxy_proto_rawDescData
}

var file_brokerproxy_v1_brokerproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_brokerproxy_v1_brokerproxy_proto_goTypes = []any{
	(*ProxyMsg)(nil),   // 0: brokerproxy.v1.ProxyMsg
	(*BrokerMsg)(nil),  // 1: brokerproxy.v1.BrokerMsg
	(*Announce)(nil),   // 2: brokerproxy.v1.Announce
	(*Ack)(nil),        // 3: brokerproxy.v1.Ack
	(*Event)(nil),      // 4: brokerproxy.v1.Event
	(*Header)(nil),     // 5: brokerproxy.v1.Header
	(*Egress)(nil),     // 6: brokerproxy.v1.Egress
	(*EgressResp)(nil), // 7: brokerproxy.v1.EgressResp
}
var file_brokerproxy_v1_brokerproxy_proto_depIdxs = []int32{
	2, // 0: brokerproxy.v1.ProxyMsg.announce:type_name -> brokerproxy.v1.Announce
	3, // 1: brokerproxy.v1.ProxyMsg.ack:type_name -> brokerproxy.v1.Ack
	6, // 2: brokerproxy.v1.ProxyMsg.egress:type_name -> brokerproxy.v1.Egress
	4, // 3: brokerproxy.v1.BrokerMsg.event:type_name -> brokerproxy.v1.Event
	7, // 4: brokerproxy.v1.BrokerMsg.egress_resp:type_name -> brokerproxy.v1.EgressResp
	5, // 5: brokerproxy.v1.Egress.headers:type_name -> brokerproxy.v1.Header
	5, // 6: brokerproxy.v1.EgressResp.headers:type_name -> brokerproxy.v1.Header
	0, // 7: brokerproxy.v1.BrokerProxy.Session:input_type -> brokerproxy.v1.ProxyMsg
	1, // 8: brokerproxy.v1.BrokerProxy.Session:output_type -> brokerproxy.v1.BrokerMsg
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_brokerproxy_v1_brokerproxy_proto_init() }
func file_brokerproxy_v1_brokerproxy_proto_init() {
	if File_brokerproxy_v1_brokerproxy_proto != nil {
		return
	}
	file_brokerproxy_v1_brokerproxy_proto_msgTypes[0].OneofWrappers = []any{
		(*ProxyMsg_Announce)(nil),
		(*ProxyMsg_Ack)(nil),
		(*ProxyMsg_Egress)(nil),
	}
	file_brokerproxy_v1_brokerproxy_proto_msgTypes[1].OneofWrappers = []any{
		(*BrokerMsg_Event)(nil),
		(*BrokerMsg_EgressResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brokerproxy_v1_brokerproxy_proto_rawDesc), len(file_brokerproxy_v1_brokerproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brokerproxy_v1_brokerproxy_proto_goTypes,
		DependencyIndexes: file_brokerproxy_v1_brokerproxy_proto_depIdxs,
		MessageInfos:      file_brokerproxy_v1_brokerproxy_proto_msgTypes,
	}.Build()
	File_brokerproxy_v1_brokerproxy_proto = out.File
	file_brokerproxy_v1_brokerproxy_proto_goTypes = nil
	file_brokerproxy_v1_brokerproxy_proto_depIdxs = nil
}
